### ISSUE TITLE
Convert to python3

### ISSUE THREAD

**Issue by mantielero** [aleksandrbazhin/ellipsoid_fit_python#1]
It is easy to convert this to python3. 

Just replacing the *print* calls to *print()* calls in **get_calibration_ellipsoid.py** and replacing the *xrange* calls with *range* calls in **ellipsoid_fit.py**.

**Comment by aleksandrbazhin** [comment]
I'll fix it. By the time of writing code matplotlib was unavailable for python 3, as far as I remember. Glad that code is useful.

**Comment by aleksandrbazhin** [comment]
Works in python 3 now
