### ISSUE TITLE
Rotation in ellipsoid_plot function is incorrect.

### ISSUE THREAD

**Issue by AlanKuurstra** [aleksandrbazhin/ellipsoid_fit_python#3]
Assuming rotation parameter of the ellipsoid_plot function is meant to take the evecs matrix (as is the case in plot_ellipsoid.py), then in ellipsoid_fit.ellipsoid_plot (line 87 of ellipsoid_fit.py), the rotation matrix needs to be inverted.  

ie. Line 87 should be:
[x[i, j], y[i, j], z[i, j]] = np.dot(rotation,[x[i, j], y[i, j], z[i, j]]) + center

**Comment by aleksandrbazhin** [comment]
Hi, thanks for feedback. 
Actually, I borrowed this code from https://github.com/minillinim/ellipsoid - you can report there as well.
I tried to replicate bug by generating random sample on axis-aligned ellipsoid, before realizing that `np.dot(rotation, [x[i, j], y[i, j], z[i, j]])` (proposed) and `np.dot([x[i, j], y[i, j], z[i, j]], rotation)` (current version) is exactly the same and is `rotation[0]*x[i, j] + rotation[1]*y[i, j] + rotation[2]*z[i, j]`. 
Could you please attach the input that is causing the error? There sure are bugs in that repository, I will try to fix them later.

**Comment by AlanKuurstra** [comment]
According to the matlab code (https://www.mathworks.com/matlabcentral/fileexchange/24693-ellipsoid-fit), evecs "contains the radii directions as columns of the 3x3 matrix". Therefore, in order for the evecs matrix to rotate a vector [1,0,0] on the unit sphere to the correct location on the ellipsoid, one should use:
np.dot(evecs,[1,0,0]) right?

Maybe I'm missing something.

I'll try to create an example if I find some time.

**Comment by aleksandrbazhin** [comment]
As for my previous answer - I was mistaken, of course rotation is a matrix. But opposed to Matlab code here evecs and rotation contain radii directions as rows not columns. I don't remember why I did it, probably to be able to extract ith eigenvector with evecs[i]. Maybe it was not a good idea as it may cause confusion.
Here I transpose eigenvectors before returning
https://github.com/aleksandrbazhin/ellipsoid_fit_python/blob/331dfb35ec1d23d4190d2703d48b9904d848260a/ellipsoid_fit.py#L143

**Comment by AlanKuurstra** [comment]
Oh okay, I see.  I missed the transpose when I glanced over the code.
If that's the case, then the plotting should actually be fine and this issue can be closed.
