### ISSUE TITLE
Wrong return function

### ISSUE THREAD

**Issue by YJonmo** [aleksandrbazhin/ellipsoid_fit_python#4]
Hi there,

The return of the "ellipsoid_fit.py" is "return center, radii, evecs, v, chi2" but the "plot_ellipsoid.py" is asking for "center, evecs, radii = ellipsoid_fit(data2)". 
So I guess it should be changed to "center, radii, evecs, v, chai = ellipsoid_fit(data2)".

Cheers,

**Comment by YJonmo** [comment]
Sorry please remove the post, I think I was using the older version of the repo.

**Comment by aleksandrbazhin** [comment]
Thank you for report anyway. Closing issue.
