### ISSUE TITLE
Is this package suitable for calibrating an Accelerometer? 

### ISSUE THREAD

**Issue by EdXian** [aleksandrbazhin/ellipsoid_fit_python#7]
Hi @aleksandrbazhin ,
I am interested about this package. Is it possible to use 'ellipsoid_fit_python' to calibrate a static accelerometer ? I am trying to find some useful method to calibrate an accelerometer or a Magnetic sensor. 
Thanks!!

**Comment by aleksandrbazhin** [comment]
Hi. I wrote this code to calibrate Magnetic sensors specifically and was satisfied with results. Have not tried to do it for the last 5 years though. As far as I remember, there is different process and math for accelerometers, but I am not sure.
Also it is a loose port of Matlab code, the link to original project is in the description.
